### ISSUE TITLE
Controller Routes

### ISSUE THREAD

**Issue by jwilferd10** [AidanGuarniere/forum-finder#15]
# Create Controller Routes
- Create a home-routes.js file
    - Needs a Forums.findAll that'll include Comment and Username (Vote/Fav add later)
    - Needs a Forums.findOne that'll include the aforementioned models
    - Login
- Create a dashboard-routes.js file

## Additional Notes:
Currently I'm unsure how to test the home-routes.js and dashboard-routes.js without some handlebars set up on the front-end. That said, we'll look through this code and ensure everything looks solid before the eventual tests.

**Comment by jwilferd10** [comment]
# Update:
The two control routes have been pushed up to GitHub. I've saved a copy on my local repository but it's also best to have another up here. There's more work to be done on these routes, like the ability to edit posts and not just forums. What's needed will hopefully be discussed, worked on, and finished.

**Comment by AidanGuarniere** [comment]
MVP versions of these routes now published
